default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_react_hipaa_starter_development

test:
  <<: *default
  database: rails_react_hipaa_starter_test

production:
  <<: *default
  database: rails_react_hipaa_starter_production
  username: rails_react_hipaa_starter
  password: <%= ENV["RAILS_REACT_HIPAA_STARTER_DATABASE_PASSWORD"] %>

